version: '3.8'

services:
  web:
    image: docker-getsimple-cms
    container_name: getsimple-web
    ports:
      - "8080:80"
    volumes:
      - web_data:/var/www/html
    environment:
      GETSIMPLE_VERSION: 3.3.19
      DEBIAN_FRONTEND: noninteractive
    working_dir: /var/www/html
    restart: always